/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* Configure pins and initialize registers */
void ADC_0_initialization(void)
{

	// Disable digital input buffer
	ADC_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	ADC_set_pull_mode(PORT_PULL_OFF);

	ADC_0_init();
}

void TIMER_10MS_initialization(void)
{

	TIMER_10MS_init();
}

void TIMER_10US_initialization(void)
{

	TIMER_10US_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PA0 */
	PA0_set_level(false);
	PA0_set_dir(PORT_DIR_IN);
	PA0_set_pull_mode(PORT_PULL_UP);
	PA0_set_inverted(false);
	PA0_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	/* PORT setting on PB4 */
	PB4_set_level(false);
	PB4_set_dir(PORT_DIR_IN);
	PB4_set_pull_mode(PORT_PULL_UP);
	PB4_set_inverted(false);
	PB4_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	/* PORT setting on PA3 */
	PA3_set_level(false);
	PA3_set_dir(PORT_DIR_IN);
	PA3_set_pull_mode(PORT_PULL_UP);
	PA3_set_inverted(false);
	PA3_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	/* PORT setting on PA2 */
	ADC_EN_set_level(false);
	ADC_EN_set_dir(PORT_DIR_IN);
	ADC_EN_set_pull_mode(PORT_PULL_UP);
	ADC_EN_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	/* PORT setting on PA4 */
	BTN_set_level(false);
	BTN_set_dir(PORT_DIR_IN);
	BTN_set_pull_mode(PORT_PULL_OFF);
	BTN_set_inverted(false);
	BTN_set_isc(PORT_ISC_BOTHEDGES_gc);

	/* PORT setting on PB5 */
	LED1_EN_set_level(false);
	LED1_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA5 */
	LED2_EN_set_level(false);
	LED2_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA6 */
	LED3_EN_set_level(false);
	LED3_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA7 */
	LED4_EN_set_level(false);
	LED4_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC0 */
	LED5_EN_set_level(false);
	LED5_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC1 */
	LED6_EN_set_level(false);
	LED6_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC2 */
	LED7_EN_set_level(false);
	LED7_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC3 */
	LED8_EN_set_level(false);
	LED8_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB3 */
	LED9_EN_set_level(false);
	LED9_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB0 */
	R_EN_set_level(true);
	R_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB1 */
	G_EN_set_level(true);
	G_EN_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB2 */
	B_EN_set_level(true);
	B_EN_set_dir(PORT_DIR_OUT);

	CLKCTRL_init();

	VREF_0_init();

	ADC_0_initialization();

	TIMER_10MS_initialization();

	TIMER_10US_initialization();

	CPUINT_init();

	SLPCTRL_init();

	BOD_init();
}
